### Inputs
- name: "CONSUL_CLIENT | Assert inputs | get_catalog_services.yml"
  ansible.builtin.assert:
    that:
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)       # Scheme of the Consul instance
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)           # Host of the Consul instance
      - (ENV.CONSUL.PORT.INTERNAL is defined)                                                     # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)                                 # Token to authenticate with Consul

- name: "CONSUL_CLIENT | Get registered services from Consul"
  ansible.builtin.uri:
    url: "{{ base_url }}/v1/catalog/services"
    method: GET
    headers:
      "X-Consul-Token": "{{ ENV.CONSUL.MASTER_TOKEN }}"
    return_content: true
  vars:
    base_url: "{{ ENV.CONSUL.SCHEME.INTERNAL }}://{{ ENV.CONSUL.HOST.INTERNAL }}:{{ ENV.CONSUL.PORT.INTERNAL }}"
  register: consul_registered_services

### Outputs
- name: "CONSUL_CLIENT | Set fact for registered services"
  ansible.builtin.set_fact:
    consul_registered_services: "{{ consul_registered_services.json }}"
