---

## REGISTER_SERVICE
consul_service_name: "myservice"
consul_service_port: 1234
consul_service_address: myservice.local

## CREATE_ROLE
consul_role_name: "myrole"

## CREATE_OR_ADD_CONFIG
consul_service_config:
  key1: value1
  key2: value2

## STORE_APP_CONFIG
consule_service_new_config_entry:
  key3: value3
