### Inputs
- name: "CONSUL_CLIENT | Assert inputs of 'consul/client | register_resource.yml'"
  ansible.builtin.assert:
    that:
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)       # Scheme of the Consul instance
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)           # Host of the Consul instance
      - (ENV.CONSUL.PORT.INTERNAL is defined)                                                     # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)                                 # Token to authenticate with Consul
      - (_resource_name is defined) and (_resource_name|length > 0)                                 # Name of the service
      - (_resource_id is defined) and (_resource_id|length > 0)                                   # ID of the resource
      - (_resource_address is defined) and (_resource_address|length > 0)
      # - (_resource_remote_access_service_id is defined) and (_resource_remote_access_service_id|length > 0)  # Remote access service ID                                                                                 # Meta data of the service

### Optional Inputs:
# - _consul_datacenter: Datacenter of the resource (default: fabos)
# - _consul_service_name: Name of the remote access service (default: ssh)
# - _consul_service_id: ID of the remote access service (default: random uuid)
# - _consul_service_port: Port of the remote access service (default: 22)
# - _consul_meta: Meta data of the remote access service

- name: "CONSUL_CLIENT | Set default tags for resource '{{ _resource_name }}'"
  ansible.builtin.set_fact:
    _consul_service_tags:
      - "RemoteAccessService"
      - "{{ _consul_service_name | default('ssh') }}"

- name: CONSUL_CLIENT | Add resource as node to consul
  ansible.builtin.uri:
    url: "{{ ENV.CONSUL.SCHEME.INTERNAL }}://{{ ENV.CONSUL.HOST.INTERNAL }}:{{ ENV.CONSUL.PORT.INTERNAL }}/v1/catalog/register"
    method: PUT
    headers:
      "X-Consul-Token": "{{ ENV.CONSUL.MASTER_TOKEN }}"
    body_format: json
    body:
      ID: "{{ _resource_id }}"
      Node: "{{ _resource_name }}"
      Datacenter: "{{ _consul_datacenter | default('fabos') }}"
      Address: "{{ _resource_address }}"
      NodeMeta:
        resourceId: "{{ _resource_id }}"

- name: CONSUL_CLIENT | Add Remote Access Service as consul service and link to resource
  ansible.builtin.uri:
    url: "{{ ENV.CONSUL.SCHEME.INTERNAL }}://{{ ENV.CONSUL.HOST.INTERNAL }}:{{ ENV.CONSUL.PORT.INTERNAL }}/v1/catalog/register"
    method: PUT
    headers:
      "X-Consul-Token": "{{ ENV.CONSUL.MASTER_TOKEN }}"
    body_format: json
    body:
      Node: "{{ _resource_name }}"
      Address: "{{ _resource_address }}"
      SkipNodeUpdate: true
      Service:
        ID: "{{ _resource_remote_access_service_id }}"
        Service: "{{ _consul_service_name | default('ssh') }}"
        Tags: "{{ _consul_service_tags }}"
